### ISSUE TITLE
elseif not working properly.

### ISSUE THREAD

**Issue by Aurailus** [retroverse/venus#2]
Hi there, I'm currently encountering an issue where
```
if (...) {
    ...
}
elseif (...) {
    ....
}
```
doesn't work, but
```
if (...) {
    ...
elseif (...) {
    ...
}
```
does. 

This doesn't seem intentional, and isn't very intuitive. Would it be possible to get a fix for this issue?

**Comment by retroverse** [comment]
Hi there,
thrilled someone is using an old project of mine. Additionally, I have committed a quick fix to the problem you mentioned. However, this project is not very well put together and was thrown together for a personal project a couple of years ago. So I wouldn't recommend using it for anything of particularly significant importance. As a replacement, I would highly recommend [MoonScript](https://github.com/leafo/moonscript) which originally inspired this Venus project and unlike it, remains consistently updated and supported.

**Comment by Aurailus** [comment]
Thank you so much for the fix, even though you're not maintaining this project anymore! I'll take a look at MoonScript and maybe switch over.
